//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt315_InterviewScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dt315_InterviewScore()
        {
            this.dt315_InterviewScoreAudit = new HashSet<dt315_InterviewScoreAudit>();
        }
    
        public long Id { get; set; }
        public long AssignmentId { get; set; }
        public int ProfessionalSkill { get; set; }
        public string ProfessionalSkillNote { get; set; }
        public int Responsiveness { get; set; }
        public string ResponsivenessNote { get; set; }
        public int Communication { get; set; }
        public string CommunicationNote { get; set; }
        public int ReportQuality { get; set; }
        public string ReportQualityNote { get; set; }
        public decimal Total { get; set; }
        public System.DateTime SubmittedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> ReopenedAt { get; set; }
        public string ReopenedBy { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual dt315_InterviewAssignment dt315_InterviewAssignment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt315_InterviewScoreAudit> dt315_InterviewScoreAudit { get; set; }
    }
}
