//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt314_HskExamMgmt
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public int TestDuration { get; set; }
        public int PassingScore { get; set; }
        public int ReadingCount { get; set; }
        public int WritingCount { get; set; }
        public string CreatedBy { get; set; }
        public string ExamType { get; set; }
        public string HskRatio { get; set; }
        public string Remark { get; set; }
    }
}
