//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt315_InterviewAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dt315_InterviewAssignment()
        {
            this.dt315_InterviewAssignmentAudit = new HashSet<dt315_InterviewAssignmentAudit>();
            this.dt315_InterviewScore = new HashSet<dt315_InterviewScore>();
        }
    
        public long Id { get; set; }
        public long CandidateProfileId { get; set; }
        public string InterviewerId { get; set; }
        public string Source { get; set; }
        public bool IsActive { get; set; }
        public string AssignedBy { get; set; }
        public System.DateTime AssignedAt { get; set; }
        public string RemovedBy { get; set; }
        public Nullable<System.DateTime> RemovedAt { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual dt315_InterviewCandidate dt315_InterviewCandidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt315_InterviewAssignmentAudit> dt315_InterviewAssignmentAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt315_InterviewScore> dt315_InterviewScore { get; set; }
    }
}
