//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt315_InterviewAssignmentAudit
    {
        public long Id { get; set; }
        public long AssignmentId { get; set; }
        public string Action { get; set; }
        public string ActorId { get; set; }
        public System.DateTime ActionAt { get; set; }
        public string Reason { get; set; }
        public long CandidateProfileId { get; set; }
        public string InterviewerId { get; set; }
        public string Source { get; set; }
    
        public virtual dt315_InterviewAssignment dt315_InterviewAssignment { get; set; }
    }
}
