//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt316_Report
    {
        public int Id { get; set; }
        public int IdPlan { get; set; }
        public string IdDept { get; set; }
        public Nullable<int> IdAdt { get; set; }
        public System.DateTime CreateAt { get; set; }
        public string CreateBy { get; set; }
        public string RemoveBy { get; set; }
        public Nullable<System.DateTime> RemoveAt { get; set; }
    }
}
