//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt315_InterviewCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dt315_InterviewCandidate()
        {
            this.dt315_InterviewAssignment = new HashSet<dt315_InterviewAssignment>();
        }
    
        public long Id { get; set; }
        public string ReportId { get; set; }
        public string CandidateId { get; set; }
        public bool UsesDefaultInterviewers { get; set; }
        public string OriginalFileName { get; set; }
        public string PhysicalFileName { get; set; }
        public string RelativePath { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string Sha256 { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt315_InterviewAssignment> dt315_InterviewAssignment { get; set; }
        public virtual dt315_InterviewReport dt315_InterviewReport { get; set; }
    }
}
