//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt315_InterviewScoreAudit
    {
        public long Id { get; set; }
        public long ScoreId { get; set; }
        public string Action { get; set; }
        public string ActorId { get; set; }
        public System.DateTime ActionAt { get; set; }
        public string Reason { get; set; }
        public int ProfessionalSkill { get; set; }
        public string ProfessionalSkillNote { get; set; }
        public int Responsiveness { get; set; }
        public string ResponsivenessNote { get; set; }
        public int Communication { get; set; }
        public string CommunicationNote { get; set; }
        public int ReportQuality { get; set; }
        public string ReportQualityNote { get; set; }
        public decimal Total { get; set; }
        public System.DateTime SubmittedAt { get; set; }
    
        public virtual dt315_InterviewScore dt315_InterviewScore { get; set; }
    }
}
