//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt318_Tasks
    {
        public int Id { get; set; }
        public string ChuDe { get; set; }
        public string GiaiThich { get; set; }
        public System.DateTime NgayDenHan { get; set; }
        public string TrangThai { get; set; }
        public string DuongDanThuMucChung { get; set; }
        public string DuongDanThuMucCongViec { get; set; }
        public string TrangThaiOCR { get; set; }
        public string ThongBaoOCR { get; set; }
        public Nullable<System.DateTime> ThoiGianOCR { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public string NguoiXoa { get; set; }
        public string DuongDanThuMucNguon { get; set; }
        public string MaNguon { get; set; }
    }
}
