//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt314_HskExamQuestion
    {
        public int Id { get; set; }
        public string ExamCode { get; set; }
        public int QuestionId { get; set; }
        public string LevelCode { get; set; }
        public string SectionCode { get; set; }
        public string QuestionType { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> GroupDisplayOrder { get; set; }
        public Nullable<int> QuestionOrderInGroup { get; set; }
    
        public virtual dt314_HskQuestionGroup dt314_HskQuestionGroup { get; set; }
        public virtual dt314_HskQuestions dt314_HskQuestions { get; set; }
    }
}
