//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt314_HskAnswers
    {
        public int Id { get; set; }
        public int QuesId { get; set; }
        public string DisplayText { get; set; }
        public string ImageName { get; set; }
        public bool TrueAns { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual dt314_HskQuestions dt314_HskQuestions { get; set; }
    }
}
