//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt315_InterviewDefaultInterviewer
    {
        public string ReportId { get; set; }
        public string InterviewerId { get; set; }
        public string AssignedBy { get; set; }
        public System.DateTime AssignedAt { get; set; }
    
        public virtual dt315_InterviewReport dt315_InterviewReport { get; set; }
    }
}
