//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt314_HskQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dt314_HskQuestions()
        {
            this.dt314_HskAnswers = new HashSet<dt314_HskAnswers>();
            this.dt314_HskExamQuestion = new HashSet<dt314_HskExamQuestion>();
        }
    
        public int Id { get; set; }
        public string LevelCode { get; set; }
        public string SectionCode { get; set; }
        public string QuestionType { get; set; }
        public string DisplayText { get; set; }
        public string ImageName { get; set; }
        public bool IsMultiAns { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string PartCode { get; set; }
        public Nullable<int> SourceQuestionNo { get; set; }
        public string QuestionCode { get; set; }
        public int UsageCount { get; set; }
        public Nullable<System.DateTime> LastUsedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt314_HskAnswers> dt314_HskAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt314_HskExamQuestion> dt314_HskExamQuestion { get; set; }
        public virtual dt314_HskQuestionGroup dt314_HskQuestionGroup { get; set; }
    }
}
