//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt314_HskQuestionGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dt314_HskQuestionGroup()
        {
            this.dt314_HskExamQuestion = new HashSet<dt314_HskExamQuestion>();
            this.dt314_HskQuestions = new HashSet<dt314_HskQuestions>();
        }
    
        public int Id { get; set; }
        public string LevelCode { get; set; }
        public string SectionCode { get; set; }
        public string PartCode { get; set; }
        public string GroupType { get; set; }
        public string GroupCode { get; set; }
        public string Title { get; set; }
        public string InstructionText { get; set; }
        public string SharedPassage { get; set; }
        public string SharedOptionPool { get; set; }
        public Nullable<int> SourceQuestionFrom { get; set; }
        public Nullable<int> SourceQuestionTo { get; set; }
        public int QuestionCount { get; set; }
        public bool RandomAsUnit { get; set; }
        public decimal RandomWeight { get; set; }
        public bool IsActive { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt314_HskExamQuestion> dt314_HskExamQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dt314_HskQuestions> dt314_HskQuestions { get; set; }
    }
}
